### ISSUE TITLE
Issues when downloading manually

### ISSUE THREAD

**Issue by jon-daemon** [Slluxx/AmiiboGenerator#6]
I want to  avoid connecting my CFW switch on the internet and I need to create the amiibos manually using amiibos.json.

I noticed that after copying this file in the sd card and reboot my console, the file becomes blank and there is an unusable amiibo (an `amiibos` folder is created in `sdmc:/emuiibo/amiibo`). It's probably created by emuiibo when it launches. I have to add that file using USB file transfer and delete that before restarting.
Is it possible to put that file in a different location and select that location from AmiiboGenerator so it won't be seen by emuiibo? (or just change the default location in the code).

Another thing I would like to suggest is about creating images manually.
If I enable image generation and I don't have an internet connection, it creates a blank amiibo.png. Then I can replace that image with one of my choice but it's too time consuming for hundreds of amiibos.
I was thinking to download all the images from githubusercontent using a script and put them in the sd card (like sdmc:/emuiibo/images). Then I could replace the source link in amiibos.json with the local folder path in sd card to let AmmiboGenerator grab all the necessary files from the local folder, convert them if needed, and copy them in the amiibo folder.
I tried that but it seems that it tries to connect on the internet if I enable image generation. Could you add this feature?

**Comment by Slluxx** [comment]
Why do you need to reboot your console?
Get the amiibo.json file, paste it, create all amiibos and you dont need it anymore. You can add your own images by simply placing them in [each of the desired amiibo folder](https://github.com/Slluxx/AmiiboGenerator/blob/main/source/amiibo.hpp#L131).

IIRC emuibo does not create/use or read from a file thats called amiibos.json, [nor can i find anything in the source code when searching for that](https://github.com/search?q=repo%3AXorTroll%2Femuiibo+amiibos.json&type=code).

If you still have issues ( which very much look like specific to your console), you can use [Emuiigen](https://github.com/XorTroll/emuiibo/tree/4cb95fbc01ceda87512855c4fab44bf23fd08533?tab=readme-ov-file#virtual-amiibo-creation), to create amiibos on your pc. The generation is 100% the same since i took his code and ported it to C++.

Or you can simply use 90DNS or DNS-MITM to go online. There is no drawback to doing that.

**Comment by jon-daemon** [comment]
I use DNS-MITM but I'm afraid to connect it on the internet.
Th primary goal was to generate on the go only the ones I needed, thus the reboot after using the .json file.
I finally used emuiigen on a PC and generated all of them.
Thanks.
